name: portfolio_sample
description: "A portfolio project using flutter for all platforms (android, ios, linux, macOS, web & windows)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  responsive_builder: ^0.7.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Eczar
      fonts:
        - asset: assets/fonts/Eczar-Regular.ttf
        - asset: assets/fonts/Eczar-Bold.ttf
        - asset: assets/fonts/Eczar-SemiBold.ttf
        - asset: assets/fonts/Eczar-Medium.ttf
        - asset: assets/fonts/Eczar-ExtraBold.ttf
